### PR TITLE
Add Horizontal Slider for style variations.

### PR DESCRIPTION
**Pull request by StevenDufresne**
This PR adds a component: `wporg/horizontal-slider` and makes improvements to `wporg/screenshot-preview` to make it more flexible and able to be used within `wporg/horizontal-slider`.

`wporg/horizontal-slider` is currently pretty opinionated and will work exclusively with its current usage on `wordpress.org/themes/{theme_slug}`. We can abstract it if necessary when a second use-case arises.

#### Less items than container
Screen Shot 2022-10-05 at 1 49 30 PM

#### More items than container
Screen Shot 2022-10-05 at 1 49 53 PM

#### Focus, Hover state
Screen Shot 2022-10-05 at 1 55 29 PM

## Testing
It's tricky to test this block because it isn't a real block, yet. It's front-end code that binds to an element. You could technically create an environment and bind this with the appropriate items but I'm not certain that would be worth your time at this point. I don't know.

### CODE REVIEW

**Comment by ryelle** [comment]
I've skimmed over the code and it seems fine, but I don't think I can test it without knowing what the `.wporg-horizontal-slider-js` element should look like.

The only thing I'd want to test myself is keyboard navigation - whether the slider scrolls to keep the current item in focus when it overflows. And screen reader interaction, but I think that depends on the data in `items` since it's passed down to ScreenShot.

**Comment by StevenDufresne** [comment]
Yeah, this control isn't exactly laid out how I would want it ideally, but with the current constraints....

**Here's a video with audio:**
https://d.pr/v/7p3tyr

**Here are the items:**
```
[{"title":"Default","link":"https://wp-themes.com/bjork","previewLink":"https://wp-themes.com/bjork?card_view&v=0.1.9-betaV1.1.0","caption":"View Default style variation"},{"title":"burton","link":"https://wp-themes.com/bjork?style_variation=burton","previewLink":"https://wp-themes.com/bjork?style_variation=burton&card_view&v=0.1.9-betaV1.1.0","caption":"View burton style variation"},{"title":"clayton","link":"https://wp-themes.com/bjork?style_variation=clayton","previewLink":"https://wp-themes.com/bjork?style_variation=clayton&card_view&v=0.1.9-betaV1.1.0","caption":"View clayton style variation"},{"title":"cliff","link":"https://wp-themes.com/bjork?style_variation=cliff","previewLink":"https://wp-themes.com/bjork?style_variation=cliff&card_view&v=0.1.9-betaV1.1.0","caption":"View cliff style variation"},{"title":"dolores","link":"https://wp-themes.com/bjork?style_variation=dolores","previewLink":"https://wp-themes.com/bjork?style_variation=dolores&card_view&v=0.1.9-betaV1.1.0","caption":"View dolores style variation"},{"title":"helena","link":"https://wp-themes.com/bjork?style_variation=helena","previewLink":"https://wp-themes.com/bjork?style_variation=helena&card_view&v=0.1.9-betaV1.1.0","caption":"View helena style variation"},{"title":"léon","link":"https://wp-themes.com/bjork?style_variation=léon","previewLink":"https://wp-themes.com/bjork?style_variation=léon&card_view&v=0.1.9-betaV1.1.0","caption":"View léon style variation"},{"title":"simone","link":"https://wp-themes.com/bjork?style_variation=simone","previewLink":"https://wp-themes.com/bjork?style_variation=simone&card_view&v=0.1.9-betaV1.1.0","caption":"View simone style variation"}]
```

**Comment by StevenDufresne** [comment]
I've added some more JSDoc documentation to make the structures easier to detect:
https://github.com/WordPress/wporg-mu-plugins/pull/289/files#diff-55e4cbed70b8b0eae5cd3507e78af16599df8220eabad63277396a5261a1fee9R26

**Review by ryelle — APPROVED** [review]
I think this is okay to merge, I still haven't tested it myself but the screenshots & screen recordings are really helpful. The only concern I have (which isn't a blocker here) is that the variations are links, and that & the label make it seem like it should load a new page. Maybe I'm wrong, but from the video it looks like it just changes the preview screenshot, and there's no indication of action for a screen reader user. I suspect that's on the theme directory side, though.

**Comment by StevenDufresne** [comment]
>  I suspect that's on the theme directory side, though.

Correct. It used to open the preview window, but the experience has changed. I'll update it on the directory side. What would you suggest the caption be for something that changes the preview image? It's kind of weird because it's a visual change so users using screen readers don't see the change... 

Maybe just:
"{name} style variation"

Also, in this case, would it be more ideal if it weren't a link since it doesn't navigate anymore?

**Pull request merged**
