### PR TITLE
Remove lines.

### PR DESCRIPTION
**Pull request by tellyworth**
See https://github.com/WordPress/wporg-news-2021/issues/132

### CODE REVIEW

**Comment by beafialho** [comment]
@tellyworth can you add a screenshot so I can review the changes?

**Review by iandunn — APPROVED** [review]
LGTM from a code perspective

**Comment by tellyworth** [comment]
Before:
Screen Shot 2021-12-20 at 4 55 49 pm
After:
Screen Shot 2021-12-20 at 4 56 54 pm

I'm not sure what's up with the vertical alignment on my local install, but as you can see that's separate from this PR and not caused by it.

**Comment by beafialho** [comment]
Thank you @tellyworth.

> I'm not sure what's up with the vertical alignment on my local install

Could it be the header's height, which should be `90px`? My only other comment is the word "Search" next to the magnifying glass icon shouldn't be there.

**Comment by iandunn** [comment]
I don't see the alignment issue locally, so it may be something specific to your env, or it could be a specific browser etc. IMO it shouldn't block merging this, unless you wanna combine the two.

**Comment by tellyworth** [comment]
I'm still getting a header that's taller (105.6px). But after some nuke-updating, here are cleaner screenshots.

Before:
Screen Shot 2021-12-21 at 6 41 22 pm

After:
Screen Shot 2021-12-21 at 6 42 17 pm

**Comment by beafialho** [comment]
This looks good to me 👍

**Pull request merged**
